version: '26.1.1'

services:
  db:
    image: 'mongo'
    ports:
      - 27017:27017
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
